### ISSUE TITLE
[Backend] Initial Database setup

### ISSUE THREAD

**Issue by oxyflush** [NickPriv/FryRank#1]
## Description

Discuss and decide on a database model as well as schema for the initial tables.

Some decisions:
1. What data are we storing?
2. SQL or NoSQL?
3. Where to host it?

## Acceptance Criteria

1. Decided a database model to use
4. Drafted schemas for tables that will be needed for FryRank view restaurants feature
5. Create an instance of database on the hosting site we decide to use

**Comment by NickPriv** [comment]
Here is the document: https://github.com/NickPriv/FryRank/wiki/Database-Choice-and-Schema
