### ISSUE TITLE
[UI] Create mockup for Restaurants page

### ISSUE THREAD

**Issue by NickPriv** [NickPriv/FryRank#8]
### Description ###
Before building the frontend for displaying restaurants, we should know what we want it to look like, and work backwards from there.

### Acceptance Criteria ###
The UI is done in sufficient detail that we know all details that should be displayed on this page.

**Comment by oxyflush** [comment]
Please take a look @NickPriv  https://www.figma.com/file/2HIPjMd6bBWep1jw6X28u5/FryRank-Mockups---Restaurants-Page?type=design&node-id=0-1&mode=design&t=glODg5dk9qIV3VLW-0

**Comment by NickPriv** [comment]
I added a few comments @oxyflush

**Comment by NickPriv** [comment]
Looks good, you can go on to the implementation @oxyflush
